version: '3.7'

networks:
  logstash:
    external: true
    name: localdev

services:
  logstash:
    build:
      context: .
    container_name: logstash-aws
    networks:
      - logstash
    restart: on-failure
    env_file:
      - ./conf/.env
